rule [
  ruleID "Intermolecular decarboxylative Claisen thioester condensation"
  left [
    edge [ source 1 target 2 label "-" ]
    edge [ source 6 target 7 label "-" ]
    edge [ source 9 target 10 label "-" ]
    edge [ source 10 target 12 label "-" ]
    edge [ source 12 target 13 label "-" ]
  ]
  context [
    node [ id 0 label "Ag" ]
    node [ id 1 label "S" ]
    node [ id 2 label "C" ]
    node [ id 3 label "O" ]
    node [ id 4 label "C" ]
    edge [ source 0 target 1 label "-" ]
    edge [ source 2 target 3 label "=" ]
    edge [ source 2 target 4 label "-" ]
    node [ id 5 label "Au" ]
    node [ id 6 label "S" ]
    node [ id 7 label "C" ]
    node [ id 8 label "O" ]
    node [ id 9 label "C" ]
    node [ id 10 label "C" ]
    node [ id 11 label "O" ]
    node [ id 12 label "O" ]
    node [ id 13 label "H" ]
    edge [ source 5 target 6 label "-" ]
    edge [ source 7 target 8 label "=" ]
    edge [ source 7 target 9 label "-" ]
    edge [ source 10 target 11 label "=" ]
  ]
  right [
    edge [ source 9 target 2 label "-" ]
    edge [ source 1 target 7 label "-" ]
    edge [ source 6 target 13 label "-" ]
    edge [ source 10 target 12 label "=" ]
  ]
]
